#!/usr/bin/env bash
# Stop Apache to free port 8080, make nginx.conf readable, and run Nginx as the nginx user on port 8080
service apache2 stop
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen [::]:8080 default_server ipv6only=on;/' /etc/nginx/sites-available/default
sudo -u nginx nginx
