#!/usr/bin/env bash
# shellcheck disable=SC2154
# configures nginx identically to web-01 and adds an X-Served-By response header
apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

if ! grep -q "redirect_me" /etc/nginx/sites-available/default; then
    sed -i 's|server_name _;|server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}|' /etc/nginx/sites-available/default
fi

if ! grep -q "error_page 404" /etc/nginx/sites-available/default; then
    sed -i 's|server_name _;|server_name _;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}|' /etc/nginx/sites-available/default
fi

if ! grep -q "X-Served-By" /etc/nginx/sites-available/default; then
    sed -i "s|server_name _;|server_name _;\n\tadd_header X-Served-By \$HOSTNAME;|" /etc/nginx/sites-available/default
fi

service nginx restart
