#!/usr/bin/env bash
# Nginx was configured to listen on 8080 instead of 80; fix the config and restart it
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
pkill nginx
sleep 1
service nginx start
