#!/usr/bin/env bash
# Fix the port and disable the pid directive so init loses track, then start directly
sed -i -e 's/8080/80/g' -e '/^pid /s/^/#/' /etc/nginx/sites-enabled/default /etc/nginx/nginx.conf
pkill nginx
nginx -g 'pid /tmp/nginx.pid;'
