#!/usr/bin/env bash
# installs nginx, listening on port 80, serving a page containing Holberton School
apt-get update -y
apt-get install -y nginx
echo "Holberton School for the win!" > /var/www/html/index.html
service nginx restart
