#!/usr/bin/env bash
# installs nginx and makes /redirect_me answer with a 301 redirect
apt-get update -y
apt-get install -y nginx
echo "Holberton School for the win!" > /var/www/html/index.html
if ! grep -q "redirect_me" /etc/nginx/sites-available/default; then
    sed -i 's|server_name _;|server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}|' /etc/nginx/sites-available/default
fi
service nginx restart
